### ISSUE TITLE
Реализовать модель

### ISSUE THREAD

**Issue by andrey-sikerin** [andrey-sikerin/todo_list_app_sirius#7]
## Общие требования
- Реализовать структуру (!) `TodoItem` (требования ниже)
- Реализовать расширение `TodoItem` для разбора json (требования ниже)
- Реализовать класс `FileCache` (требования ниже)
- Реализовать сохранение и загрузку `FileCache` в файл и из файла

## TodoItem
- Иммутабельная структура
- Содержит уникальный идентификатор id, если не задан пользователем - генерируется (`UUID().uuidString`)
- Содержит обязательное строковое поле - `text`
- Содержит обязательное поле важность, должно быть enum, может иметь три варианта - "неважная", "обычная" и "важная"
- Содержит дедлайн, может быть не задан, если задан - дата

## TodoItem, parsing json
- Расширение для структуры TodoItem
- Содержит функцию (`static func parse(json: Any) -> TodoItem?`) для разбора json
- Содержит вычислимое свойство (`var json: Any`) для формирования json'а
- Не сохранять в json важность, если она "обычная"
- Не сохранять в json сложные объекты (`Date`)
- Сохранять deadline только если он задан
- Обязательно использовать `JSONSerialization` (т.е. работу со словарем)

## FileCache
- Содержит закрытую для внешнего изменения, но открытую для получения коллекцию `TodoItem`
- Содержит функцию добавления новой задачи
- Содержит функцию удаления задачи (на основе id)
- Содержит функцию сохранения всех дел в файл
- Содержит функцию загрузки всех дел из файла
- Можем иметь несколько разных файлов

## Тесты
- Написать тесты

**Comment by Artem-Goldenberg** [comment]
В TodoItem, parsing json секции написано, что нельзя сложные объекты в json сохранять, а String? считается за сложный объект?
